/*
 * Copyright (c) 2014 All Rights Reserved.
 */


package com.lizhy.auto.dao.impl;

import org.mybatis.spring.support.SqlSessionDaoSupport;

import com.lizhy.auto.dao.UserDAO;
import com.lizhy.auto.model.UserDO;
import java.util.Map;
import java.util.List;
import java.util.HashMap;


/**
 * An ibatis based implementation of dao interface <tt>com.lizhy.auto.dao.UserDAO</tt>.
 *
 * This file is generated by <tt>ibatis-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>ibatis</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/user.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>ibatis-dalgen</tt> 
 * to generate this file.
 *
 * @author dalgen
 */
public class UserDAOImpl extends SqlSessionDaoSupport implements UserDAO {

	private static final String namespace="com.lizhy.auto.dao.";
	/**
	 *  Insert one <tt>UserDO</tt> object to DB table <tt>user</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into test_user(name,age,password) values (?, ?, ?)</tt>
	 *
	 *	@param user
	 *	@return Integer
	 *	@throws DataAccessException
	 */	 
	@Override
	public Integer insertUser(UserDO user) {
    	if (user == null) {
    		throw new IllegalArgumentException("Can't insert a null data object into db.");
    	}
    	
        getSqlSession().insert(namespace+"USER-INSERT-USER", user);

        return user.getId();
    }

	/**
	 *  Query DB table <tt>user</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from test_user where (age BETWEEN ? AND ?)</tt>
	 *
	 *	@return Long
	 *	@throws DataAccessException
	 */	 
	@Override
	public Long selectCountByAge() {

        return (Long) getSqlSession().selectOne(namespace+"USER-SELECT-COUNT-BY-AGE", null);

    }

	/**
	 *  Update DB table <tt>user</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update test_user set age=?, password=? where (name = ?)</tt>
	 *
	 *	@param age
	 *	@param password
	 *	@param name
	 *	@return int
	 *	@throws DataAccessException
	 */	 
	@Override
	public int updateUser(Integer age, String password, String name) {
        Map param = new HashMap();

        param.put("age", age);
        param.put("password", password);
        param.put("name", name);

        return getSqlSession().update(namespace+"USER-UPDATE-USER", param);
    }

	/**
	 *  Query DB table <tt>user</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from test_user where (name = ?)</tt>
	 *
	 *	@param name
	 *	@return List<UserDO>
	 *	@throws DataAccessException
	 */	 
	@Override
	public List<UserDO> selectByName(String name) {

        return getSqlSession().selectList(namespace+"USER-SELECT-BY-NAME", name);

    }

	/**
	 *  Query DB table <tt>user</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from test_user where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return UserDO
	 *	@throws DataAccessException
	 */	 
	@Override
	public UserDO selectById(Integer id) {

        return (UserDO) getSqlSession().selectOne(namespace+"USER-SELECT-BY-ID", id);

    }

	/**
	 *  Delete records from DB table <tt>user</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from test_user where (name = ?)</tt>
	 *
	 *	@param name
	 *	@return int
	 *	@throws DataAccessException
	 */	 
	@Override
	public int deleteByName(String name) {

        return getSqlSession().delete(namespace+"USER-DELETE-BY-NAME", name);
    }

}
