package com.lizhy.auto.dao;

import com.lizhy.auto.model.ScheduleJobLogDO;

import java.util.List;
import java.util.Map;

public interface ScheduleJobLogDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    int insert(ScheduleJobLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    int insertSelective(ScheduleJobLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    ScheduleJobLogDO selectByPrimaryKey(Long logId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    int updateByPrimaryKeySelective(ScheduleJobLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    int updateByPrimaryKey(ScheduleJobLogDO record);

    int selectJobLogListCount(Map<String, Object> param);

    List<ScheduleJobLogDO> selectJobLogList(Map<String, Object> param);
}