package com.lizhy.auto.dao;

import com.lizhy.auto.model.ScheduleTimerDO;

import java.util.List;

public interface ScheduleTimerDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_timer
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    int insert(ScheduleTimerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_timer
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    int insertSelective(ScheduleTimerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_timer
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    ScheduleTimerDO selectByPrimaryKey(Long timerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_timer
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    int updateByPrimaryKeySelective(ScheduleTimerDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_timer
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    int updateByPrimaryKey(ScheduleTimerDO record);

    int upsertSelective(ScheduleTimerDO record);

    List<ScheduleTimerDO> selectByJobId(Long jobId);
}