package com.lizhy.auto.dao;

import com.lizhy.auto.model.ScheduleExecutorDO;

import java.util.List;

public interface ScheduleExecutorDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_executor
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    int insert(ScheduleExecutorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_executor
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    int insertSelective(ScheduleExecutorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_executor
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    ScheduleExecutorDO selectByPrimaryKey(Long exeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_executor
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    int updateByPrimaryKeySelective(ScheduleExecutorDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_executor
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    int updateByPrimaryKey(ScheduleExecutorDO record);

    List<ScheduleExecutorDO> selectAllByJobId(Long jobId);

    List<ScheduleExecutorDO> selectEffective(Long jobId);
}