package com.lizhy.auto.dao;

import com.lizhy.auto.model.ScheduleJobLogDO;

public interface ScheduleJobLogDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbg.generated 2017-10-30 13:58:32
     */
    int insert(ScheduleJobLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbg.generated 2017-10-30 13:58:32
     */
    int insertSelective(ScheduleJobLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbg.generated 2017-10-30 13:58:32
     */
    int updateByPrimaryKeySelective(ScheduleJobLogDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table schedule_job_log
     *
     * @mbg.generated 2017-10-30 13:58:32
     */
    int updateByPrimaryKey(ScheduleJobLogDO record);
}