/*
 * Copyright (c) 2014 All Rights Reserved.
 */
package com.lizhy.auto.dao;

// auto generated imports
import com.lizhy.auto.model.UserDO;
import java.util.List;

/**
 * A dao interface provides methods to access database table <tt>user</tt>.
 *
 * This file is generated by <tt>ibatis-dalgen</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>ibatis</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/user.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>ibatis-dalgen</tt> 
 * to generate this file.
 *
 * @author dalgen
 */
public interface UserDAO {
	/**
	 *  Insert one <tt>UserDO</tt> object to DB table <tt>user</tt>, return primary key
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>insert into test_user(name,age,password) values (?, ?, ?)</tt>
	 *
	 *	@param user
	 *	@return Integer
	 *	@throws DataAccessException
	 */	 
	public Integer insertUser(UserDO user);

	/**
	 *  Query DB table <tt>user</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from test_user where (age BETWEEN ? AND ?)</tt>
	 *
	 *	@return Long
	 *	@throws DataAccessException
	 */	 
	public Long selectCountByAge();

	/**
	 *  Update DB table <tt>user</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>update test_user set age=?, password=? where (name = ?)</tt>
	 *
	 *	@param age
	 *	@param password
	 *	@param name
	 *	@return int
	 *	@throws DataAccessException
	 */	 
	public int updateUser(Integer age, String password, String name);

	/**
	 *  Query DB table <tt>user</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from test_user where (name = ?)</tt>
	 *
	 *	@param name
	 *	@return List<UserDO>
	 *	@throws DataAccessException
	 */	 
	public List<UserDO> selectByName(String name);

	/**
	 *  Query DB table <tt>user</tt> for records.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>select * from test_user where (id = ?)</tt>
	 *
	 *	@param id
	 *	@return UserDO
	 *	@throws DataAccessException
	 */	 
	public UserDO selectById(Integer id);

	/**
	 *  Delete records from DB table <tt>user</tt>.
	 *
   	 *  <p>
   	 *  Description for this operation is<br>
   	 *  <tt></tt>
	 *  <p>
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from test_user where (name = ?)</tt>
	 *
	 *	@param name
	 *	@return int
	 *	@throws DataAccessException
	 */	 
	public int deleteByName(String name);

}