package com.lizhy.auto.model;

import com.lizhy.BaseObject;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table schedule_executor
 *
 * @mbg.generated do_not_delete_during_merge 2017-10-20 11:04:14
 */
public class ScheduleExecutorDO extends BaseObject {
    /**
     * Database Column Remarks:
     *   执行者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_executor.exe_id
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    private Long exeId;

    /**
     * Database Column Remarks:
     *   执行者所属任务ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_executor.job_id
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    private Long jobId;

    /**
     * Database Column Remarks:
     *   执行者名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_executor.exe_name
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    private String exeName;

    /**
     * Database Column Remarks:
     *   执行者IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_executor.exe_url
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    private String exeUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_executor.exe_interface
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    private String exeInterface;

    /**
     * Database Column Remarks:
     *   状态 0 无效 1 有效 2未来有效
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_executor.status
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   生效时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_executor.effective_time
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    private Long effectiveTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_executor.create_time
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    private Long createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_executor.update_time
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    private Long updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_executor.exe_id
     *
     * @return the value of schedule_executor.exe_id
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public Long getExeId() {
        return exeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_executor.exe_id
     *
     * @param exeId the value for schedule_executor.exe_id
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public void setExeId(Long exeId) {
        this.exeId = exeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_executor.job_id
     *
     * @return the value of schedule_executor.job_id
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_executor.job_id
     *
     * @param jobId the value for schedule_executor.job_id
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_executor.exe_name
     *
     * @return the value of schedule_executor.exe_name
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public String getExeName() {
        return exeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_executor.exe_name
     *
     * @param exeName the value for schedule_executor.exe_name
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public void setExeName(String exeName) {
        this.exeName = exeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_executor.exe_url
     *
     * @return the value of schedule_executor.exe_url
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public String getExeUrl() {
        return exeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_executor.exe_url
     *
     * @param exeUrl the value for schedule_executor.exe_url
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public void setExeUrl(String exeUrl) {
        this.exeUrl = exeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_executor.exe_interface
     *
     * @return the value of schedule_executor.exe_interface
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public String getExeInterface() {
        return exeInterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_executor.exe_interface
     *
     * @param exeInterface the value for schedule_executor.exe_interface
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public void setExeInterface(String exeInterface) {
        this.exeInterface = exeInterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_executor.status
     *
     * @return the value of schedule_executor.status
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_executor.status
     *
     * @param status the value for schedule_executor.status
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_executor.effective_time
     *
     * @return the value of schedule_executor.effective_time
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public Long getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_executor.effective_time
     *
     * @param effectiveTime the value for schedule_executor.effective_time
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public void setEffectiveTime(Long effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_executor.create_time
     *
     * @return the value of schedule_executor.create_time
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_executor.create_time
     *
     * @param createTime the value for schedule_executor.create_time
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_executor.update_time
     *
     * @return the value of schedule_executor.update_time
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_executor.update_time
     *
     * @param updateTime the value for schedule_executor.update_time
     *
     * @mbg.generated 2017-10-20 11:04:14
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }
}