package com.lizhy.auto.model;

import com.lizhy.BaseObject;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table schedule_job_log
 *
 * @mbg.generated do_not_delete_during_merge 2017-11-26 15:46:15
 */
public class ScheduleJobLogDO extends BaseObject {
    /**
     * Database Column Remarks:
     *   日志ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_log.log_id
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    private Long logId;

    /**
     * Database Column Remarks:
     *   本条日志所属任务ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_log.job_id
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    private Long jobId;

    /**
     * Database Column Remarks:
     *   本条日志执行者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_log.executor_id
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    private Long executorId;

    /**
     * Database Column Remarks:
     *   执行url
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_log.exe_url
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    private String exeUrl;

    /**
     * Database Column Remarks:
     *   执行接口
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_log.exe_interface
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    private String exeInterface;

    /**
     * Database Column Remarks:
     *   任务通知时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_log.notify_start
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    private Long notifyStart;

    /**
     * Database Column Remarks:
     *   任务通知返回时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_log.notify_end
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    private Long notifyEnd;

    /**
     * Database Column Remarks:
     *   任务执行结束时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_log.finished
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    private Long finished;

    /**
     * Database Column Remarks:
     *   执行返回信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_log.ret_msg
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    private String retMsg;

    /**
     * Database Column Remarks:
     *   通知状态:0 未通知1 已通知－返回成功2 已通知－返回失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_log.notify_status
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    private Integer notifyStatus;

    /**
     * Database Column Remarks:
     *   执行状态:0 未执行1 成功2 执行失败
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_log.return_status
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    private Integer returnStatus;

    /**
     * Database Column Remarks:
     *   警告发送次数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job_log.alert_times
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    private Integer alertTimes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_log.log_id
     *
     * @return the value of schedule_job_log.log_id
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_log.log_id
     *
     * @param logId the value for schedule_job_log.log_id
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_log.job_id
     *
     * @return the value of schedule_job_log.job_id
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_log.job_id
     *
     * @param jobId the value for schedule_job_log.job_id
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_log.executor_id
     *
     * @return the value of schedule_job_log.executor_id
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public Long getExecutorId() {
        return executorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_log.executor_id
     *
     * @param executorId the value for schedule_job_log.executor_id
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public void setExecutorId(Long executorId) {
        this.executorId = executorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_log.exe_url
     *
     * @return the value of schedule_job_log.exe_url
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public String getExeUrl() {
        return exeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_log.exe_url
     *
     * @param exeUrl the value for schedule_job_log.exe_url
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public void setExeUrl(String exeUrl) {
        this.exeUrl = exeUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_log.exe_interface
     *
     * @return the value of schedule_job_log.exe_interface
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public String getExeInterface() {
        return exeInterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_log.exe_interface
     *
     * @param exeInterface the value for schedule_job_log.exe_interface
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public void setExeInterface(String exeInterface) {
        this.exeInterface = exeInterface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_log.notify_start
     *
     * @return the value of schedule_job_log.notify_start
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public Long getNotifyStart() {
        return notifyStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_log.notify_start
     *
     * @param notifyStart the value for schedule_job_log.notify_start
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public void setNotifyStart(Long notifyStart) {
        this.notifyStart = notifyStart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_log.notify_end
     *
     * @return the value of schedule_job_log.notify_end
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public Long getNotifyEnd() {
        return notifyEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_log.notify_end
     *
     * @param notifyEnd the value for schedule_job_log.notify_end
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public void setNotifyEnd(Long notifyEnd) {
        this.notifyEnd = notifyEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_log.finished
     *
     * @return the value of schedule_job_log.finished
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public Long getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_log.finished
     *
     * @param finished the value for schedule_job_log.finished
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public void setFinished(Long finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_log.ret_msg
     *
     * @return the value of schedule_job_log.ret_msg
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public String getRetMsg() {
        return retMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_log.ret_msg
     *
     * @param retMsg the value for schedule_job_log.ret_msg
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public void setRetMsg(String retMsg) {
        this.retMsg = retMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_log.notify_status
     *
     * @return the value of schedule_job_log.notify_status
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public Integer getNotifyStatus() {
        return notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_log.notify_status
     *
     * @param notifyStatus the value for schedule_job_log.notify_status
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public void setNotifyStatus(Integer notifyStatus) {
        this.notifyStatus = notifyStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_log.return_status
     *
     * @return the value of schedule_job_log.return_status
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public Integer getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_log.return_status
     *
     * @param returnStatus the value for schedule_job_log.return_status
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public void setReturnStatus(Integer returnStatus) {
        this.returnStatus = returnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job_log.alert_times
     *
     * @return the value of schedule_job_log.alert_times
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public Integer getAlertTimes() {
        return alertTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job_log.alert_times
     *
     * @param alertTimes the value for schedule_job_log.alert_times
     *
     * @mbg.generated 2017-11-26 15:46:15
     */
    public void setAlertTimes(Integer alertTimes) {
        this.alertTimes = alertTimes;
    }
}