package com.lizhy.auto.model;

import com.lizhy.BaseObject;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table schedule_timer
 *
 * @mbg.generated do_not_delete_during_merge 2017-10-26 13:57:30
 */
public class ScheduleTimerDO extends BaseObject {
    /**
     * Database Column Remarks:
     *   时间规则ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_timer.timer_id
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    private Long timerId;

    /**
     * Database Column Remarks:
     *   时间规则所属任务ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_timer.job_id
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    private Long jobId;

    /**
     * Database Column Remarks:
     *   时间规则 采用Quartz的cron的时间规则定义 
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_timer.cron
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    private String cron;

    /**
     * Database Column Remarks:
     *   生效时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_timer.effective_time
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    private Long effectiveTime;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_timer.create_time
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    private Long createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_timer.update_time
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    private Long updateTime;

    /**
     * Database Column Remarks:
     *   状态 0 无效 1 有效 2未来有效 一个定时任务只能允许一条有效时间规则
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_timer.status
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_timer.timer_id
     *
     * @return the value of schedule_timer.timer_id
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public Long getTimerId() {
        return timerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_timer.timer_id
     *
     * @param timerId the value for schedule_timer.timer_id
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public void setTimerId(Long timerId) {
        this.timerId = timerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_timer.job_id
     *
     * @return the value of schedule_timer.job_id
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_timer.job_id
     *
     * @param jobId the value for schedule_timer.job_id
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_timer.cron
     *
     * @return the value of schedule_timer.cron
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public String getCron() {
        return cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_timer.cron
     *
     * @param cron the value for schedule_timer.cron
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public void setCron(String cron) {
        this.cron = cron;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_timer.effective_time
     *
     * @return the value of schedule_timer.effective_time
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public Long getEffectiveTime() {
        return effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_timer.effective_time
     *
     * @param effectiveTime the value for schedule_timer.effective_time
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public void setEffectiveTime(Long effectiveTime) {
        this.effectiveTime = effectiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_timer.create_time
     *
     * @return the value of schedule_timer.create_time
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public Long getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_timer.create_time
     *
     * @param createTime the value for schedule_timer.create_time
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public void setCreateTime(Long createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_timer.update_time
     *
     * @return the value of schedule_timer.update_time
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public Long getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_timer.update_time
     *
     * @param updateTime the value for schedule_timer.update_time
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public void setUpdateTime(Long updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_timer.status
     *
     * @return the value of schedule_timer.status
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_timer.status
     *
     * @param status the value for schedule_timer.status
     *
     * @mbg.generated 2017-10-26 13:57:30
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}