package com.lizhy.auto.model;

import com.lizhy.BaseObject;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table schedule_job
 *
 * @mbg.generated do_not_delete_during_merge 2017-10-18 14:11:03
 */
public class ScheduleJobDO extends BaseObject {
    /**
     * Database Column Remarks:
     *   任务ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.job_id
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    private Long jobId;

    /**
     * Database Column Remarks:
     *   任务名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.job_name
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    private String jobName;

    /**
     * Database Column Remarks:
     *   执行机器：0 第一台 1 顺序选择 2 随机选择 3 全部执行
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.execute_select
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    private Boolean executeSelect;

    /**
     * Database Column Remarks:
     *   通知保证：0 只执行一次 不管是否成功 1 保证成功 当一次执行不成功时，取下一主机执行，如果一直不成功，则到所有主机执行一遍为止 2 保证成功(当上次任务未完成时，不执行，否则跟1一至)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.execute_rule
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    private Boolean executeRule;

    /**
     * Database Column Remarks:
     *   任务描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.job_desc
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    private String jobDesc;

    /**
     * Database Column Remarks:
     *   任务执行的超时时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.timeout
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    private Integer timeout;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.create_time
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    private Integer createTime;

    /**
     * Database Column Remarks:
     *   失效时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.update_time
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    private Integer updateTime;

    /**
     * Database Column Remarks:
     *   1:启用，1：禁用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column schedule_job.status
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.job_id
     *
     * @return the value of schedule_job.job_id
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.job_id
     *
     * @param jobId the value for schedule_job.job_id
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.job_name
     *
     * @return the value of schedule_job.job_name
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.job_name
     *
     * @param jobName the value for schedule_job.job_name
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.execute_select
     *
     * @return the value of schedule_job.execute_select
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public Boolean getExecuteSelect() {
        return executeSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.execute_select
     *
     * @param executeSelect the value for schedule_job.execute_select
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public void setExecuteSelect(Boolean executeSelect) {
        this.executeSelect = executeSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.execute_rule
     *
     * @return the value of schedule_job.execute_rule
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public Boolean getExecuteRule() {
        return executeRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.execute_rule
     *
     * @param executeRule the value for schedule_job.execute_rule
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public void setExecuteRule(Boolean executeRule) {
        this.executeRule = executeRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.job_desc
     *
     * @return the value of schedule_job.job_desc
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public String getJobDesc() {
        return jobDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.job_desc
     *
     * @param jobDesc the value for schedule_job.job_desc
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public void setJobDesc(String jobDesc) {
        this.jobDesc = jobDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.timeout
     *
     * @return the value of schedule_job.timeout
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public Integer getTimeout() {
        return timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.timeout
     *
     * @param timeout the value for schedule_job.timeout
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public void setTimeout(Integer timeout) {
        this.timeout = timeout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.create_time
     *
     * @return the value of schedule_job.create_time
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.create_time
     *
     * @param createTime the value for schedule_job.create_time
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.update_time
     *
     * @return the value of schedule_job.update_time
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.update_time
     *
     * @param updateTime the value for schedule_job.update_time
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column schedule_job.status
     *
     * @return the value of schedule_job.status
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column schedule_job.status
     *
     * @param status the value for schedule_job.status
     *
     * @mbg.generated 2017-10-18 14:11:03
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}